#define SYS_read        0
#define SYS_write       1
#define SYS_readv       19
#define SYS_writev      20
#define SYS_sendto      44
#define SYS_recvfrom    45
#define SYS_sendmsg     46
#define SYS_recvmsg     47
#define SYS_recvmmsg    299
#define SYS_sendmmsg    307